### ISSUE TITLE
LEGACY - Breaks with FF 57

### ISSUE THREAD

**Issue by tlhackque** [twpol/cz-homepage#7]
Needs to be ported to WebExtensions - or will die with Firefox 57, due out in a few weeks.

**Comment by twpol** [comment]
This is being tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1322442 but the lack of supported features in WebExtensions currently means it is unlikely that we can migrate at this time.

**Comment by anewuser** [comment]
It'd be nice for your users if you added a note about it to the extension description (https://addons.mozilla.org/firefox/addon/chatzilla/). Your site actually says "ChatZilla works on Mozilla Firefox 57.0" (http://chatzilla.hacksrus.com/).
